# Generated by Django 5.1.4 on 2024-12-28 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('A', 'Alimentos'), ('AS', 'Alquiler y Servicios'), ('S', 'Shopping'), ('R', 'Regalos'), ('E', 'Entretenimiento'), ('V', 'Viajes'), ('S', 'Sueldo'), ('O', 'Otros')], default='O', max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('informe', models.CharField(max_length=25)),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('GAS', 'Gasto'), ('BAL', 'Balance General')], default='BAL', max_length=3)),
                ('periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=10)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'unique_together': {('año', 'tipo', 'periodo')},
            },
        ),
    ]
