# Generated by Django 5.1.4 on 2024-12-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('A', 'Alimentos'), ('AS', 'Alquiler y Servicios'), ('S', 'Shopping'), ('R', 'Regalos'), ('E', 'Entretenimiento'), ('V', 'Viajes'), ('S', 'Sueldo'), ('O', 'Otros')], default='O', max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('informe', models.CharField(max_length=25)),
                ('categoria', models.CharField(choices=[('ING', 'Ingreso'), ('GAS', 'Gasto'), ('BAL', 'Balance General')], default='BAL', max_length=3)),
                ('periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=10)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('año', 'informe'), name='unico_informe_por_año')],
            },
        ),
    ]
