# Generated by Django 5.1.4 on 2024-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informes',
            name='año',
            field=models.PositiveIntegerField(),
        ),
    ]
