# Generated by Django 5.1.4 on 2024-12-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.RemoveConstraint(
            model_name='informe',
            name='unico_informe_por_año',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='informe',
            unique_together={('año', 'categoria', 'periodo')},
        ),
    ]
