# Generated by Django 5.1.4 on 2024-12-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_transaccion_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ('-fecha',), 'verbose_name': 'Transaccion', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
