# Generated by Django 5.1.4 on 2024-12-22 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_transaccion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='categoria',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 15, 55, 37, 428452)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='informe',
            unique_together={('año', 'tipo', 'periodo')},
        ),
    ]
