# Generated by Django 5.1.4 on 2024-12-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_informes_año'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informes',
            new_name='Informe',
        ),
        migrations.AddConstraint(
            model_name='informe',
            constraint=models.UniqueConstraint(fields=('año', 'informe'), name='unico_informe_por_año'),
        ),
    ]
