# Generated by Django 5.1.4 on 2024-12-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_categoria_informe_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
