# Generated by Django 5.1.4 on 2024-12-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_transaccion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='mes_fin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='mes_inicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informe',
            name='periodo',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestre'), ('ANUAL', 'Anual')], default='ANUAL', max_length=10),
        ),
    ]
