# Generated by Django 5.1.4 on 2024-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_informe_mes_fin_informe_mes_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='mes_fin',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='informe',
            name='mes_inicio',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
