# Generated by Django 5.1.4 on 2024-12-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
