# Generated by Django 5.1.4 on 2024-12-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_informe_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informe',
            unique_together={('año', 'tipo', 'periodo', 'mes_inicio', 'mes_fin')},
        ),
    ]
